### PR TITLE
Fix CQW-117 custom 404 page

### PR DESCRIPTION
**Pull request by rpietraszko**
TODO:
* [X] Fix positioning issues after recent changes on master
* [X] Replace class used by buttons

Reviewers:
* [x] @beatadelura 
* [ ] @MagdaMalinowska 
* [ ] @pjar 
* [x] @kruszczynski

### CODE REVIEW

**Comment by beatadelura** [comment]
Below view on Safari:
* I can't scroll down
* Font has black color
zrzut ekranu 2016-03-01 o 09 28 45

**Comment by beatadelura** [comment]
Mobile view below:
* Is it correct that `Uh-oh` is near header?
zrzut ekranu 2016-03-01 o 09 32 05

**Comment by rpietraszko** [comment]
@beatadelura - did you pulled recent changes from branch? seems to work good

image

**Comment by beatadelura** [comment]
@rpietraszko I did pull now and Safari is ok. Only mobile issue still exist :)

**Comment by AdamMankowski** [comment]
This is supposed to look like this

**Comment by beatadelura** [comment]
Ok, I just thought that it's a bug ;)

**Pull request merged**
