### PR TITLE
Add Google analytics Tracking code

### PR DESCRIPTION
**Pull request by AdamMankowski**
## TO DO:
* [X] Add Google analytics Tracking code to all layouts

---

Review:
* [x] @beatadelura
* [ ] @kruszczynski
* [x] @pjar
* [ ] @rpietraszko
* [ ] @MagdaMalinowska

### CODE REVIEW

**Comment by pjar** [comment]
If this is 3x the same code, maybe it could go to a partial?

**Comment by MagdaMalinowska** [comment]
Agree with @pjar

**Comment by rpietraszko** [comment]
Since it's javascript - maybe let's create a `scripts` folder inside `source/javascripts` and then in the layout:
```
= javascript_include_tag 'scripts/analytics'
```
(same for previously added hotjar heatmap script)
```
= javascript_include_tag 'scripts/heatmap'
```

**Comment by AdamMankowski** [comment]
You guys are right. I will change it.

**Comment by AdamMankowski** [comment]
I've created partials. Pls check again

**Comment by kruszczynski** [comment]
Squash it!

**Pull request merged**
